export const data = [
    {
        projectId: 2234001,
        projectName: "Temple Construction",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 150,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Iron Received"
    },
    {
        projectId: 2234002,
        projectName: "Bridge Construction",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 40,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Foundation Completed"
    },
    {
        projectId: 2234003,
        projectName: "Road Construction",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 210,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    },
    {
        projectId: 2234004,
        projectName: "Bridge Repair",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 180,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    },
    {
        projectId: 2234005,
        projectName: "Bridge Repair",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 300,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    },
    {
        projectId: 2234006,
        projectName: "Bridge Repair",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 100,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    },
    {
        projectId: 2234007,
        projectName: "Bridge Repair",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 180,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    },
    {
        projectId: 2234008,
        projectName: "Bridge Repair",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 250,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    },
    {
        projectId: 2234009,
        projectName: "Temple Construction",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 150,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Iron Received"
    },
    {
        projectId: 2234010,
        projectName: "Bridge Construction",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 230,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Foundation Completed"
    },
    {
        projectId: 2234011,
        projectName: "Road Construction",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 210,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    },
    // {
    //     projectId: 2234012,
    //     projectName: "Bridge Repair",
    //     projectManager: "Ram Kishan",
    //     startDate: "27/12/2020",
    //     siteAddress: "#25 Rampur UP",
    //     railwayStation: "Rampur Junction",
    //     budget: 180,
    //     endDate: "12/11/2028",
    //     supplier1: "Cement Supplier",
    //     contactPerson: "Babulal",
    //     phone: "1234567890",
    //     email: "babulal@babulal.com",
    //     projectStatus: "Cement Ordered"
    // },
    // {
    //     projectId: 2234013,
    //     projectName: "Bridge Repair",
    //     projectManager: "Ram Kishan",
    //     startDate: "27/12/2020",
    //     siteAddress: "#25 Rampur UP",
    //     railwayStation: "Rampur Junction",
    //     budget: 300,
    //     endDate: "12/11/2028",
    //     supplier1: "Cement Supplier",
    //     contactPerson: "Babulal",
    //     phone: "1234567890",
    //     email: "babulal@babulal.com",
    //     projectStatus: "Cement Ordered"
    // },
    // {
    //     projectId: 2234014,
    //     projectName: "Bridge Repair",
    //     projectManager: "Ram Kishan",
    //     startDate: "27/12/2020",
    //     siteAddress: "#25 Rampur UP",
    //     railwayStation: "Rampur Junction",
    //     budget: 100,
    //     endDate: "12/11/2028",
    //     supplier1: "Cement Supplier",
    //     contactPerson: "Babulal",
    //     phone: "1234567890",
    //     email: "babulal@babulal.com",
    //     projectStatus: "Cement Ordered"
    // },
    {
        projectId: 2234015,
        projectName: "Bridge Repair",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 50,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    },
    {
        projectId: 2234016,
        projectName: "Bridge Repair",
        projectManager: "Ram Kishan",
        startDate: "27/12/2020",
        siteAddress: "#25 Rampur UP",
        railwayStation: "Rampur Junction",
        budget: 250,
        endDate: "12/11/2028",
        supplier1: "Cement Supplier",
        contactPerson: "Babulal",
        phone: "1234567890",
        email: "babulal@babulal.com",
        projectStatus: "Cement Ordered"
    }
]